eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  book-service:
    endpoints:
      endpoint:
        uri: http://book-service/api/books
  user-service:
    endpoints:
      endpoint:
        uri: http://user-service/api/users   
    
    
